eProsima/Micro-XRCE-DDS-Agent

include/uxr/agent/datareader/DataReader.hpp
include/uxr/agent/transport/SerialLayer.hpp
include/uxr/agent/transport/SerialServerLinux.hpp
include/uxr/agent/transport/TCPServerLinux.hpp
include/uxr/agent/transport/TCPServerWindows.hpp
include/uxr/agent/transport/UDPServerLinux.hpp
include/uxr/agent/transport/UDPServerWindows.hpp
src/cpp/processor/Processor.cpp
src/cpp/transport/SerialServerLinux.cpp
src/cpp/transport/Server.cpp
src/cpp/transport/TCPServerLinux.cpp
src/cpp/transport/TCPServerWindows.cpp
src/cpp/transport/UDPServerLinux.cpp
src/cpp/transport/UDPServerWindows.cpp

This pull request provide the following improvements:
- First, concurrence error was solved in the TCP server. This error took place when the reader thread closed the socket while the sender was trying to send data and vice-versa.
- Second, Windows transports (UDP/TCP) have been stabilized in both Agent and Client.

Transport stabilization

---

src/cpp/types/TopicPubSubType.cpp

This pull fixes a bug related with large data transmission.
Apart from this, users should defined `data_writer` and `data_reader` according with issue #4.

Large data hotfix

---

include/uxr/agent/transport/Server.hpp
include/uxr/agent/transport/serial/SerialServerBase.hpp
include/uxr/agent/transport/tcp/TCPServerBase.hpp
include/uxr/agent/transport/udp/UDPServerBase.hpp
src/cpp/processor/Processor.cpp
src/cpp/transport/serial/SerialServerBase.cpp
src/cpp/transport/tcp/TCPServerBase.cpp
src/cpp/transport/udp/UDPServerBase.cpp

This pull request changed the create session behaviour.
Now when a Client, in _no-client-key mode_, tries to create a session with different `ClientKey` but the same `EndPoint`, the previous session will be removed.

Change create session behaviour

---

CMakeLists.txt
include/uxr/agent/client/session/Session.hpp
include/uxr/agent/client/session/stream/OutputStream.hpp
include/uxr/agent/message/InputMessage.hpp
include/uxr/agent/message/OutputMessage.hpp
include/uxr/agent/processor/Processor.hpp
include/uxr/agent/types/SubMessageHeader.hpp
include/uxr/agent/types/XRCETypes.hpp
microxrce_agent.cpp
src/cpp/processor/Processor.cpp
src/cpp/transport/Server.cpp
src/cpp/transport/serial/serial_protocol.c
src/cpp/transport/tcp/TCPServerLinux.cpp
src/cpp/transport/tcp/TCPServerWindows.cpp

This pull request adds support for the performance test. It has the following changes:
* The CMakeLists.txt has been modified with a new flag for activating the performance test.
* A new submessage (PERFORMANCE) has been introduced.
The payload of this new submessage is composed by the epoch_time (64 bit), following by an array of octets with variable length. This submessage has two main purposes: 1) receive raw data from the Client in order to test the throughput, and 2) send echoes message for measuring the latency between the Agent and the Client.

Performance test

---

CMakeLists.txt
include/uxr/agent/client/session/Session.hpp
include/uxr/agent/client/session/stream/InputStream.hpp
include/uxr/agent/message/InputMessage.hpp
include/uxr/agent/processor/Processor.hpp
src/cpp/processor/Processor.cpp

This pull request implements fragmentation for input messages received from the Clients.
It has involved the following changes:
- `push_fragment` and `pop_fragment_message` function have been added to `ReliableInputStream`.
- `get_raw_header` has been added to `InputMessage`.
- `process_fragment_submessage` has been implemented in `Processor`.
Before approve this pull request:

Input fragmentation

---

cmake/common/eprosima_libraries.cmake
include/uxr/agent/client/session/Session.hpp
include/uxr/agent/client/session/stream/InputStream.hpp
include/uxr/agent/client/session/stream/OutputStream.hpp
include/uxr/agent/message/OutputMessage.hpp
include/uxr/agent/types/MessageHeader.hpp
include/uxr/agent/types/SubMessageHeader.hpp
include/uxr/agent/utils/SeqNum.hpp
src/cpp/processor/Processor.cpp
src/cpp/types/MessageHeader.cpp
src/cpp/types/SubMessageHeader.cpp
test/integration/cross_serialization/AgentSerialization.cpp
test/unittest/xrce/XRCETests.cpp

This pull request adds support for output message fragmentation (from Agent to Client).
This new feature has involved the following changes:
- `OutputStream` class has been modified adding `push_submessage` and `get_next_message` functions.
- `OutputMessage` class has been modified adding `append_fragment` function.
- `Processor` class has been adapted to new `push_submessage` and `get_next_message` functions come from `OutputStream`.

Output fragmentation

---

include/uxr/agent/transport/Server.hpp
include/uxr/agent/transport/serial/SerialServerLinux.hpp
include/uxr/agent/transport/tcp/TCPServerLinux.hpp
include/uxr/agent/transport/tcp/TCPServerWindows.hpp
include/uxr/agent/transport/udp/UDPServerLinux.hpp
include/uxr/agent/transport/udp/UDPServerWindows.hpp
microxrce_agent.cpp
src/cpp/transport/Server.cpp
src/cpp/transport/serial/SerialServerLinux.cpp
src/cpp/transport/tcp/TCPServerLinux.cpp
src/cpp/transport/tcp/TCPServerWindows.cpp
src/cpp/transport/udp/UDPServerLinux.cpp
src/cpp/transport/udp/UDPServerWindows.cpp

- Discovery disables by default.
- New flag `--discovery` to enable the discovery system.
- Transports `UDPServer` and `TCPServer` with the same API in Linux and Windows.

Refs #3846. Added discovery flag to the agent.

---

include/uxr/agent/types/XRCETypes.hpp
src/cpp/processor/Processor.cpp
src/cpp/types/XRCETypes.cpp
test/unittest/xrce/XRCETests.cpp

This pull request fixed the deviation with respect the DDS-XRCE that `SampleData` structure has.

Refs #3588. Removed size from topic data. [4437]

---

include/uxr/agent/processor/Processor.hpp
include/uxr/agent/types/XRCETypes.hpp
include/uxr/agent/utils/Time.hpp
src/cpp/Root.cpp
src/cpp/processor/Processor.cpp
src/cpp/types/XRCETypes.cpp
test/blackbox/tree/TreeTests.cpp
test/integration/cross_serialization/AgentSerialization.cpp
test/unittest/Common.cpp

This pull request contains the following changes:
-   XRCE types have been modified according to the new version of the standard (ptc/19-03-27).
-   A time synchronization mechanism has been added using the new submessages TIEMSTAMP and TIMESTAMP_REPLY.

Time synchronization [5170]

---

include/uxr/agent/client/ProxyClient.hpp
include/uxr/agent/datareader/DataReader.hpp
include/uxr/agent/datawriter/DataWriter.hpp
include/uxr/agent/object/XRCEObject.hpp
include/uxr/agent/participant/Participant.hpp
include/uxr/agent/publisher/Publisher.hpp
include/uxr/agent/subscriber/Subscriber.hpp
include/uxr/agent/topic/Topic.hpp
src/cpp/Root.cpp
src/cpp/client/ProxyClient.cpp
src/cpp/datareader/DataReader.cpp
src/cpp/datawriter/DataWriter.cpp
src/cpp/participant/Participant.cpp
src/cpp/processor/Processor.cpp
src/cpp/publisher/Publisher.cpp
src/cpp/subscriber/Subscriber.cpp
src/cpp/topic/Topic.cpp
test/mock/ProxyClient/uxr/agent/client/ProxyClient.hpp

This pull request fixes the `DataReader` closing.
Previously, when a `ProxyClient` was destroyed with a running `read_task`, an interlock took place.

DataReader closing

---

include/uxr/agent/transport/discovery/DiscoveryServer.hpp
include/uxr/agent/transport/discovery/DiscoveryServerLinux.hpp
include/uxr/agent/transport/discovery/DiscoveryServerWindows.hpp
include/uxr/agent/transport/util/InterfaceLinux.hpp
include/uxr/agent/transport/util/InterfaceWindows.hpp
src/cpp/transport/discovery/DiscoveryServer.cpp
src/cpp/transport/discovery/DiscoveryServerLinux.cpp
src/cpp/transport/discovery/DiscoveryServerWindows.cpp
src/cpp/transport/tcp/TCPv4AgentLinux.cpp
src/cpp/transport/tcp/TCPv4AgentWindows.cpp
src/cpp/transport/tcp/TCPv6AgentLinux.cpp
src/cpp/transport/tcp/TCPv6AgentWindows.cpp
src/cpp/transport/udp/UDPv4AgentLinux.cpp
src/cpp/transport/udp/UDPv4AgentWindows.cpp
src/cpp/transport/udp/UDPv6AgentLinux.cpp
src/cpp/transport/udp/UDPv6AgentWindows.cpp

This PR modifies the `DiscoveryServer` approach.
Now, Agents such as `UDPv4Agent` are in charge of obtains the list of network interfaces and passing them to the `DiscoveryServer`.

DiscoveryServer modification [7903]

---

include/uxr/agent/p2p/InternalClientManager.hpp
include/uxr/agent/transport/p2p/AgentDiscoverer.hpp
include/uxr/agent/transport/p2p/AgentDiscovererLinux.hpp
include/uxr/agent/transport/tcp/TCPv4AgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv6AgentLinux.hpp
include/uxr/agent/transport/udp/UDPv6AgentLinux.hpp
src/cpp/p2p/InternalClient.cpp
src/cpp/p2p/InternalClientManager.cpp
src/cpp/transport/p2p/AgentDiscoverer.cpp
src/cpp/transport/p2p/AgentDiscovererLinux.cpp
src/cpp/transport/tcp/TCPv4AgentLinux.cpp
src/cpp/transport/tcp/TCPv6AgentLinux.cpp
src/cpp/transport/udp/UDPv4AgentLinux.cpp
src/cpp/transport/udp/UDPv6AgentLinux.cpp

This PR refactors P2P server.
First, P2P was removed from TCP and UDPv6 server, where there is not available implementation.
Second, the server interface methods were renamed with a more apropiate approach.

P2P refactor

---

include/uxr/agent/middleware/fast/FastEntities.hpp
include/uxr/agent/middleware/fast/FastMiddleware.hpp
src/cpp/middleware/fast/FastEntities.cpp
src/cpp/middleware/fast/FastMiddleware.cpp

This PR refactors FastEntities
* Creating a common `FastListener` using as the listener in `FastParticipant`, `FastDataWriter`, `FastDataReader`, `FastRequester` and `FastReplier`.
* Modifying the hierarchy where `FastDataWriter` and `FastDataReader` contains a reference to `FastPublisher` and `FastSubscriber` instead to `FastParticipant`.

Refactor FastRTPS entities

---

CMakeLists.txt
src/cpp/transport/serial/TermiosAgentLinux.cpp

According to the POSIX, you need to use cfsetispeed/cfsetospeed instead of working with raw termios struct. 
This PR fixed https://github.com/micro-ROS/micro-ros-build/issues/107

Fix termios speed settings according to the POSIX

---

CMakeLists.txt
cmake/SuperBuild.cmake
cmake/packaging/Config.cmake.in

This PR changes the default `UAGENT_ISOLATED_INSTALL` to OFF to address https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/166 and changes the naming from FastRTPS to FastDDS.
Integration tests pass here: https://github.com/eProsima/Micro-XRCE-DDS/pull/51#issuecomment-636822136

Default isolated install and FastDDS

---

CMakeLists.txt
include/uxr/agent/config.hpp.in
include/uxr/agent/transport/serial/SerialAgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv4AgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv4AgentWindows.hpp
include/uxr/agent/transport/tcp/TCPv6AgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv6AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv4AgentLinux.hpp
include/uxr/agent/transport/udp/UDPv4AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv6AgentLinux.hpp
include/uxr/agent/transport/udp/UDPv6AgentWindows.hpp

This PR adds a CMake flag which allows setting the server buffer size in order to optimize the memory profiling for particular applications.

Server buffer size

---

CMakeLists.txt
cmake/SuperBuild.cmake
include/uxr/agent/config.hpp.in
include/uxr/agent/utils/ArgumentParser.hpp
microxrce_agent.cpp
src/cpp/transport/serial/PseudoTerminalAgentLinux.cpp
src/cpp/transport/serial/TermiosAgentLinux.cpp

This PR addresses the following changes:
* Disable CLI11 library, via CMakeLists option.
* Provide with a built-in argument parser, in case CLI profile is disabled.
* Fix `PseudoTerminalAgent::start()` method not returning `true` when initialization was performed successfully.
* Updates foonathan tag to working version

Refs #8722. Option to disable CLI; add custom argparser [#8856]

---

CMakeLists.txt

micro-ROS Agent uses the CLI_PROFILE approach. Disabling CLI_PROFILE results in `micro_ros_agent` executable not being compiled.

Hotfix: fix micro-ROS Agent

---

include/uxr/agent/utils/ArgumentParser.hpp

Parsing the arguments by reference (that exist on the stack) creates
a race condition. The thread may execute after the stack was destroyed
causing a segfault.

Parse arguments to thread by value instead of reference

---

include/uxr/agent/utils/ArgumentParser.hpp

* Parse arguments to thread by value instead of reference
Parsing the arguments by reference (that exist on the stack) creates
a race condition. The thread may execute after the stack was destroyed
causing a segfault.
* Add missing cases for create_agent_thread template specialization
Co-authored-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>

Parse arguments to thread by value instead of reference (#183)

---

cmake/SuperBuild.cmake

This PR removes the compilation of Build Tools for Fast-DDS, not required because we are only using the library

Fix Fast-DDS build tools

---

include/uxr/agent/utils/ArgumentParser.hpp
src/cpp/AgentInstance.cpp
src/cpp/utils/ArgumentParser.cpp

Fix help when executable is not named MicroXRCEAgent, as in micro_ros_agent.

Improve usage message: fetch executable name

---

include/uxr/agent/client/session/stream/OutputStream.hpp

This PR adds a warning when a received topic from the middleware is bigger that the best effort stream where it should be placed.

Warning on best effor MTU overflow

---

src/cpp/transport/Server.cpp
src/cpp/transport/serial/TermiosAgentLinux.cpp

Add flush after serial port is opened, to avoid processing previous messages.
Also, server read timeout was 1 millisecond, changed to 1 second.

Add flush to open serial port

---

CMakeLists.txt

CMAKE_SYSTEM_NAME is set to ```Android``` by Android NDK's toolchain file. This should never affect a normal build.

Add Linux transport code to Android build

---

src/cpp/middleware/fastdds/FastDDSEntities.cpp

Internal DataWriters and DataReaders were not being deleted on Agent FastDDS Publisher and Subscriber delete methods:
https://github.com/eProsima/Micro-XRCE-DDS-Agent/blob/904221fdf69cfce712e4ad78a7784d6c7901c1a1/src/cpp/middleware/fastdds/FastDDSEntities.cpp#L489-L493
This implies that `delete_publisher` may fail, as explained on [FastDDS documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/publisher/publisher/createPublisher.html#deleting-a-publisher):
> A Publisher can only be deleted if all Entities belonging to the Publisher (DataWriters) have already been deleted. Otherwise, the function will issue an error and the Publisher will not be deleted.
This bug caused a thread/memory leak and random response problems using services/clients with reconnection …

Add sub entities destruction on FastDDS entities

---

src/cpp/transport/tcp/TCPv4AgentLinux.cpp

This options allows the agent to reuse the socket from a previously closed agent.
Otherwise we need to wait for the tcp `TIME_WAIT` timeout.
CI: https://github.com/eProsima/Micro-XRCE-DDS/pull/130

Add reuse socket to TCP agent

---

include/uxr/agent/transport/stream_framing/StreamFramingProtocol.hpp

compilation on linux, because ssize_t not defined, 
add an #include <sys/types.h> to fulfill the needed types

fix linux compile

---

src/cpp/processor/Processor.cpp

Related: https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/312

Implement GET_STATUS implementation result

---

src/cpp/transport/serial/MultiSerialAgentLinux.cpp
src/cpp/transport/serial/MultiTermiosAgentLinux.cpp

For certain ARM architectures, select returned the following `errno` for `tv_usec >= 1 second`:
> EINVAL The value contained within timeout is invalid.

Fix select() timeout format

---

include/uxr/agent/message/InputMessage.hpp
src/cpp/transport/Server.cpp

In order to prioritize Heartbeats in the incoming XRCE message queue, the incoming XRCE submessage is pre-deserialized to check: 
1. There is one and only one submessage in the message
2. This submessage is a Heartbeat.
In order to do so, some check has to be done in order to avoid wrong or invalid XRCE messages.

Fix exception on Heartbeat filter

---

src/cpp/middleware/fastdds/FastDDSEntities.cpp
src/cpp/middleware/fastdds/FastDDSMiddleware.cpp
src/cpp/replier/Replier.cpp
src/cpp/requester/Requester.cpp

Related issue: https://github.com/eProsima/Micro-XRCE-DDS-Client/issues/331

Fix requester and replier reuse behaviour

---

include/uxr/agent/middleware/Middleware.hpp
src/cpp/middleware/fast/FastMiddleware.cpp
src/cpp/middleware/fastdds/FastDDSMiddleware.cpp

As discussed on micro-ros/micro-ros-agent#182
The way this works is that if you set the domain-id to 255 on the client (an ID which is otherwise outside of the allowed range), it will be overridden by the value specified in the reference.

Allow overriding the client's domain ID through reference

---

include/uxr/agent/middleware/Middleware.hpp
include/uxr/agent/middleware/fastdds/FastDDSMiddleware.hpp
src/cpp/middleware/fastdds/FastDDSMiddleware.cpp

There was a need to select `ROS_DOMAIN_ID` in firmware without recompiling. Comparing this changes https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/322 and this PR https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/331 I prepared overriding client domain id. This change will override the clients domain (only when it is `255` - safe value due to the smaller domain limit) to the `ROS_DOMAIN_ID` configured as an environmental variable in e. g. micro-ros-agent docker container.  
Tested on Nucleo-L476RG publisher example and ROSbot 2R firmware.
Here are the changes inside firmware https://github.com/husarion/rosbot_ros2_firmware/pull/20.
I prepared prebuilt docker container with these changes `husarion/micro-ros-agent:humble-overrice-domain-id`. 
This is the example compose for ROSbot …

Override domain_id with ROS_DOMAIN_ID provided by the agent

---

include/uxr/agent/message/InputMessage.hpp
include/uxr/agent/types/XRCETypes.hpp
src/cpp/datareader/DataReader.cpp
src/cpp/datawriter/DataWriter.cpp
src/cpp/participant/Participant.cpp
src/cpp/processor/Processor.cpp
src/cpp/publisher/Publisher.cpp
src/cpp/replier/Replier.cpp
src/cpp/requester/Requester.cpp
src/cpp/subscriber/Subscriber.cpp
src/cpp/topic/Topic.cpp

Integration tests running on https://github.com/eProsima/Micro-XRCE-DDS/pull/162 :heavy_check_mark:

Fix deserialization endianness

---

include/uxr/agent/utils/ArgumentParser.hpp
src/cpp/transport/serial/MultiTermiosAgentLinux.cpp
src/cpp/transport/serial/TermiosAgentLinux.cpp

Replace https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/341 to trigger CI. See: https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/341#issuecomment-1711174707.
Closes #340
Ensure that the baud rate is set in the termios attributes when compiling with `clang` on macOS.

Enable termios baudrate configuration for macOS

---

src/cpp/middleware/fastdds/FastDDSMiddleware.cpp

This PR enables the feature introduced in https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/333 to be used with REF and XML participants

Enable Domain Override on Reference and XML Participant
