DEFAULT_FASTRTPS_PROFILES.xml
README.md
include/micrortps/agent/datareader/DataReader.hpp
include/micrortps/agent/datawriter/DataWriter.hpp
include/micrortps/agent/participant/Participant.hpp
include/micrortps/agent/topic/Topic.hpp
include/micrortps/agent/types/XRCETypes.hpp
src/cpp/Root.cpp
src/cpp/client/ProxyClient.cpp
src/cpp/datareader/DataReader.cpp
src/cpp/datawriter/DataWriter.cpp
src/cpp/libdev/MessageOutput.cpp
src/cpp/participant/Participant.cpp
src/cpp/topic/Topic.cpp
src/cpp/types/XRCETypes.cpp
test/unittest/root/CMakeLists.txt

Added entities creation by reference functionality.

Refs #3139. Added entitites creation by reference.

---

include/uxr/agent/message/OutputMessage.hpp
include/uxr/agent/utils/Functions.hpp
test/unittest/xrce/CMakeLists.txt

Takes the MTU size from the configuration.
Solves [https://github.com/eProsima/Micro-XRCE-DDS-Client/issues/24](https://github.com/eProsima/Micro-XRCE-DDS-Client/issues/24)

Take MTU from configuration.

---

CMakeLists.txt

Minor change in Windows installer.

Minor change in release review

---

src/cpp/Root.cpp

This pull request adds an XMLParser error output.

XMLParser error output

---

README.md

This pull request fixes the documentation README links.

README links

---

include/uxr/agent/participant/Participant.hpp
include/uxr/agent/types/TopicPubSubType.hpp
include/uxr/agent/types/XRCETypes.hpp
src/cpp/participant/Participant.cpp
src/cpp/processor/Processor.cpp
src/cpp/types/TopicPubSubType.cpp
src/cpp/types/XRCETypes.cpp
test/integration/cross_serialization/AgentSerialization.cpp

This pull request modifies ACKNACK and HEARTBEAT submessages adding a uint8_t stream_id member.

ACKNACK and HEARTBEAT modifications

---

Dockerfile
README.md

This pull request adds the Dockerfile needed for the automated building in Docker Hub. It is related to issue #26.

Refs #3821. Added Dockerfile.

---

include/uxr/agent/participant/Participant.hpp
include/uxr/agent/types/TopicPubSubType.hpp
src/cpp/participant/Participant.cpp
src/cpp/types/TopicPubSubType.cpp

This pull request adapts Agent to Fast RTPS 1.7.0 Release.
Here are the results of the integration and unit tests (proof of the crime):
- [Unit tests](http://jenkins.eprosima.com:8080/job/MicroRTPS-Agent%20Manual/53/)
- [Integration tests](http://ci.intranet.eprosima.com:8080/job/MicroRTPS-Integration%20Manual%20Linux/47/)

Adapted to Fast RTPS 1.7.0 Release

---

microxrce_agent.cpp

This pull request adds CLI support for setting the baudrate in Serial transport.
This pull request is related to #43.

Refs #4332. Add baudrate CLI [4431]

---

CMakeLists.txt
include/uxr/agent/transport/discovery/DiscoveryServer.hpp
include/uxr/agent/transport/discovery/DiscoveryServerLinux.hpp
include/uxr/agent/transport/discovery/DiscoveryServerWindows.hpp
include/uxr/agent/transport/tcp/TCPServerLinux.hpp
include/uxr/agent/transport/tcp/TCPServerWindows.hpp
include/uxr/agent/transport/udp/UDPServerLinux.hpp
include/uxr/agent/transport/udp/UDPServerWindows.hpp
microxrce_agent.cpp
src/cpp/transport/discovery/DiscoveryServer.cpp
src/cpp/transport/discovery/DiscoveryServerLinux.cpp
src/cpp/transport/discovery/DiscoveryServerWindows.cpp
src/cpp/transport/tcp/TCPServerWindows.cpp
src/cpp/transport/udp/UDPServerWindows.cpp

This pull request adds Discovery functionality for Windows.
On the other hand, it adds an interface for the discovery server.

Discovery on Windows [4412]

---

src/cpp/datareader/DataReader.cpp

Fixed an issue with the Delivery control with samples unlimited value.

Fixed max_sample at datareader [5039]

---

include/uxr/agent/datareader/DataReader.hpp
include/uxr/agent/transport/Server.hpp
include/uxr/agent/transport/discovery/DiscoveryServer.hpp
include/uxr/agent/transport/p2p/AgentDiscoverer.hpp
include/uxr/agent/transport/tcp/TCPServerLinux.hpp
include/uxr/agent/transport/tcp/TCPServerWindows.hpp
src/cpp/datareader/DataReader.cpp
src/cpp/transport/Server.cpp
src/cpp/transport/discovery/DiscoveryServer.cpp
src/cpp/transport/p2p/AgentDiscoverer.cpp
src/cpp/transport/tcp/TCPServerLinux.cpp
src/cpp/transport/tcp/TCPServerWindows.cpp

This pull request modifies the thread management pattern. `std::unique_ptr<std::thread>` have been changed by `std::thread`.
Before accepting this pull request accept the following:

Threads Pattern [4889]

---

.gitmodules
CMakeLists.txt
test/blackbox/tree/CMakeLists.txt
test/unittest/CMakeLists.txt
test/unittest/agent/CMakeLists.txt
test/unittest/client/session/stream/CMakeLists.txt
test/unittest/middleware/ced/CMakeLists.txt
test/unittest/transport/serial/CMakeLists.txt
test/unittest/types/CMakeLists.txt
test/unittest/utils/CMakeLists.txt

Add third-party CMake tools.
Add Sanitaze possibilities to our tests.

Add Sanitizers [5474][5475]

---

include/uxr/agent/middleware/ced/CedMiddleware.hpp

This pull request adds the CedMiddleware documentation using Doxygen comments.

CedMiddleware documentation [4633]

---

Dockerfile

- Fix Micro XRCE-DDS Agent v1.1.0 compilation issues.
- Simplify installation step.
- Adds entrypoint.

Refs #4285. Improves docker image.

---

include/uxr/agent/utils/CLI.hpp
microxrce_agent.cpp

A small improvement of the idea developed in #101 
close #100
close #101

Wait for POSIX signals [6371]

---

CMakeLists.txt
cmake/Soversion.cmake
cmake/SuperBuild.cmake
test/unittest/agent/CMakeLists.txt

This pull request update _FastRTPS_ to v1.8.3 and _FastCDR_ to v1.0.10,

FastRTPS v1.8.3

---

CMakeLists.txt
cmake/SuperBuild.cmake
include/uxr/agent/client/ProxyClient.hpp
src/cpp/client/ProxyClient.cpp
src/cpp/processor/Processor.cpp
src/cpp/transport/udp/UDPServerWindows.cpp

This pull requests updates `spdlog` logger to version 1.4.2. It fix Windows logger.

spdlog update

---

src/cpp/transport/udp/UDPv4AgentLinux.cpp
src/cpp/transport/udp/UDPv6AgentLinux.cpp

This pull request fixes UDP message reception for both IPv4 and IPv6.

Bugfix UDP message reception

---

include/uxr/agent/transport/tcp/TCPv4AgentWindows.hpp
include/uxr/agent/transport/tcp/TCPv6AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv4AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv6AgentWindows.hpp
src/cpp/transport/tcp/TCPv4AgentWindows.cpp
src/cpp/transport/tcp/TCPv6AgentWindows.cpp
src/cpp/transport/udp/UDPv4AgentWindows.cpp
src/cpp/transport/udp/UDPv6AgentWindows.cpp

This PR adds windows support for error handling

Error handling windows

---

colcon.pkg

This PR adds the colcon.pkg file.

colcon.pkg

---

CMakeLists.txt
include/uxr/agent/processor/Processor.hpp
include/uxr/agent/transport/util/Interface.hpp
include/uxr/agent/transport/util/InterfaceLinux.hpp
include/uxr/agent/transport/util/InterfaceWindows.hpp
include/uxr/agent/types/SubMessageHeader.hpp
src/cpp/datareader/DataReader.cpp
src/cpp/p2p/InternalClient.cpp
src/cpp/processor/Processor.cpp
src/cpp/transport/discovery/DiscoveryServerLinux.cpp
src/cpp/transport/discovery/DiscoveryServerWindows.cpp
src/cpp/transport/udp/UDPv4AgentLinux.cpp
src/cpp/transport/udp/UDPv4AgentWindows.cpp
src/cpp/transport/udp/UDPv6AgentLinux.cpp
src/cpp/transport/udp/UDPv6AgentWindows.cpp
src/cpp/types/SubMessageHeader.cpp

This PR is related to https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/142.
It introduces some changes made during the testing of the aforementioned PR.
Before merge:

Fix fragmentation [7903]

---

include/uxr/agent/scheduler/FCFSScheduler.hpp
include/uxr/agent/transport/TransportRc.hpp
include/uxr/agent/transport/tcp/TCPServerBase.hpp
include/uxr/agent/transport/tcp/TCPv4AgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv4AgentWindows.hpp
include/uxr/agent/transport/tcp/TCPv6AgentLinux.hpp
include/uxr/agent/transport/tcp/TCPv6AgentWindows.hpp
src/cpp/transport/Server.cpp
src/cpp/transport/serial/SerialAgentLinux.cpp
src/cpp/transport/tcp/TCPv4AgentLinux.cpp
src/cpp/transport/tcp/TCPv4AgentWindows.cpp
src/cpp/transport/tcp/TCPv6AgentLinux.cpp
src/cpp/transport/tcp/TCPv6AgentWindows.cpp
src/cpp/transport/udp/UDPv4AgentLinux.cpp
src/cpp/transport/udp/UDPv4AgentWindows.cpp
src/cpp/transport/udp/UDPv6AgentLinux.cpp
src/cpp/transport/udp/UDPv6AgentWindows.cpp

This PR fixes the error handler for TCP servers.

Fix error handler

---

src/cpp/transport/Server.cpp
src/cpp/transport/tcp/TCPv4AgentLinux.cpp
src/cpp/transport/tcp/TCPv4AgentWindows.cpp
src/cpp/transport/tcp/TCPv6AgentLinux.cpp
src/cpp/transport/tcp/TCPv6AgentWindows.cpp

This PR fixes Windows TCP servers and some Valgrind Memcheck errors.

Fix Windows TCP servers

---

src/cpp/middleware/ced/CedMiddleware.cpp

This PR simplifies the `CedMiddleware` and adds suffix handling for `Topic`s, `DataWriter`s and `DataReader`s.

CedMiddleware simplification

---

include/uxr/agent/transport/tcp/TCPv4AgentWindows.hpp
include/uxr/agent/transport/tcp/TCPv6AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv4AgentWindows.hpp
include/uxr/agent/transport/udp/UDPv6AgentWindows.hpp
src/cpp/transport/Server.cpp
src/cpp/transport/tcp/TCPv4AgentLinux.cpp
src/cpp/transport/tcp/TCPv4AgentWindows.cpp
src/cpp/transport/tcp/TCPv6AgentLinux.cpp
src/cpp/transport/tcp/TCPv6AgentWindows.cpp

This PR adds some minor improvements in TCP servers.

TCP improvements

---

Dockerfile

This PR fixes the Dockerfile interaction mode that causes error during DockerHub build.

Fix Dockerfile interaction mode

---

include/uxr/agent/datareader/DataReader.hpp
include/uxr/agent/datawriter/DataWriter.hpp
include/uxr/agent/publisher/Publisher.hpp
include/uxr/agent/replier/Replier.hpp
include/uxr/agent/requester/Requester.hpp
include/uxr/agent/subscriber/Subscriber.hpp
include/uxr/agent/topic/Topic.hpp
src/cpp/client/ProxyClient.cpp
src/cpp/datareader/DataReader.cpp
src/cpp/datawriter/DataWriter.cpp
src/cpp/middleware/fastdds/FastDDSEntities.cpp
src/cpp/publisher/Publisher.cpp
src/cpp/replier/Replier.cpp
src/cpp/requester/Requester.cpp
src/cpp/subscriber/Subscriber.cpp
src/cpp/topic/Topic.cpp

This PR refactors XRCE Entities and removes shared pointers between entities and keeps a shared pointer to the owner proxy client in order to access middleware

Ref #8401. Refactor XRCE entities.

---

Dockerfile

This PR fixes the installation in Dockerfile using `UAGENT_ISOLATED_INSTALL` option.

Fix installation in Dockerfile

---

CMakeLists.txt

This PR updates Client version to v1.2.3.
Before merge:

Update Client version

---

include/uxr/agent/utils/ArgumentParser.hpp

Please check that `./MicroXRCEAgent udp4 -p 8080 -v6` execution command now works when `UAGENT_CLI_PROFILE=OFF` before merging.

Allow numerical values to be appended to short CLI opts variant

---

include/uxr/agent/utils/ArgumentParser.hpp
src/cpp/AgentInstance.cpp
src/cpp/utils/ArgumentParser.cpp

See related [issue](https://github.com/micro-ROS/micro-ROS-Agent/issues/35).

Fix showing help when no transport is specified

---

include/uxr/agent/utils/ArgumentParser.hpp

Fix changes introduced in #194.

Fix help method signature

---

include/uxr/agent/processor/Processor.hpp
include/uxr/agent/transport/Server.hpp
src/cpp/processor/Processor.cpp
src/cpp/transport/Server.cpp

This will allow to implement a ping feature between a client and an agent, without the need of establishing a XRCE session.

Process get_info without a session established

---

src/cpp/transport/discovery/DiscoveryServerLinux.cpp

Merge when https://github.com/eProsima/Micro-XRCE-DDS/pull/62

Fix discovery multicast address

---

CMakeLists.txt
include/uxr/agent/p2p/InternalClient.hpp
src/cpp/p2p/InternalClient.cpp
test/case/CMakeLists.txt

Merge when CI passes: https://github.com/eProsima/Micro-XRCE-DDS/pull/63 and https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/217

Refactor usage of uxrUDPPlatform

---

include/uxr/agent/transport/endpoint/CustomEndPoint.hpp
include/uxr/agent/utils/ArgumentParser.hpp
src/cpp/transport/serial/MultiTermiosAgentLinux.cpp
src/cpp/transport/serial/TermiosAgentLinux.cpp

Hi all. I ported agent to Android. These two patches are needed to build with Android NDK based on llvm.

Build agent with Android NDK

---

include/uxr/agent/message/InputMessage.hpp
include/uxr/agent/scheduler/FCFSScheduler.hpp
include/uxr/agent/scheduler/PacketScheduler.hpp
include/uxr/agent/transport/Server.hpp
src/cpp/transport/Server.cpp

This is a PoC, a better approach should be taken. DO NOT MERGE

Incoming heartbeats filter

---

CMakeLists.txt
include/uxr/agent/transport/can/CanAgentLinux.hpp
include/uxr/agent/transport/endpoint/CanEndPoint.hpp
include/uxr/agent/transport/util/InterfaceLinux.hpp
include/uxr/agent/utils/ArgumentParser.hpp
src/cpp/AgentInstance.cpp
src/cpp/processor/Processor.cpp
src/cpp/transport/Server.cpp
src/cpp/transport/can/CanAgentLinux.cpp
src/cpp/utils/ArgumentParser.cpp

TODO:
Related:
- https://github.com/eProsima/Micro-XRCE-DDS/pull/114
- https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/278

Add CAN FD functionality

---

CMakeLists.txt
cmake/SuperBuild.cmake
test/blackbox/tree/CMakeLists.txt
test/unittest/CMakeLists.txt
test/unittest/agent/CMakeLists.txt
test/unittest/client/session/stream/CMakeLists.txt
test/unittest/middleware/ced/CMakeLists.txt
test/unittest/transport/serial/CMakeLists.txt
test/unittest/types/CMakeLists.txt
test/unittest/utils/CMakeLists.txt

Signed-off-by: Pablo Garrido <pablogs9@gmail.com>

Remove Sanitizer CMake module

---

src/cpp/transport/can/CanAgentLinux.cpp

Related:
- https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/298
- https://github.com/micro-ROS/micro_ros_renesas2estudio_component/pull/23
- https://github.com/micro-ROS/micro_ros_renesas_testbench/pull/61
- https://github.com/micro-ROS/micro_ros_renesas_demos/pull/26
Test CI:
- https://github.com/eProsima/Micro-XRCE-DDS/pull/122

Add CAN payload len on first frame byte

---

include/uxr/agent/client/ProxyClient.hpp
include/uxr/agent/processor/Processor.hpp
include/uxr/agent/transport/SessionManager.hpp
src/cpp/client/ProxyClient.cpp
src/cpp/processor/Processor.cpp

CI: https://github.com/eProsima/Micro-XRCE-DDS/pull/136

Implement hard liveliness check

---

src/cpp/middleware/fastdds/FastDDSMiddleware.cpp

Signed-off-by: Pablo Garrido <pablogs9@gmail.com>

Fix default QoS in Requester and Replier

---

src/cpp/transport/stream_framing/StreamFramingProtocol.cpp

Signed-off-by: Pablo Garrido <pablogs9@gmail.com>

Replace system_clock with steady_clock
